name: Reusable workflow example

on:
  workflow_call:
    inputs:
      test-value:
        required: true
        type: string

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - name: echo some stuff
      run: |
        echo "This is a reusable workflow example"
        echo "test value: ${{ inputs.test-value }}"
