name: Reusable workflow example

on:
  workflow_call:
    inputs:
      test-value:
        required: true
        type: string

env:
  TEST_VALUE: ${{ inputs.test-value }}

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: echo some stuff
      run: |
        echo "This is a reusable workflow example"
        echo "test value: $TEST_VALUE"
