name: "Playwright Action"
description: "An example action that outputs messages to the console."

on:
  workflow_call:
    inputs:
      workflow_run:
        description: "The workflow run object (e.g., github.event.workflow_run)."
        required: false

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Set Workflow Run Environment Variable
        env:
          WORKFLOW_RUN: ${{ toJson(inputs.workflow_run) }}
        run: |
          echo "Workflow Run: $WORKFLOW_RUN"

      - name: Print Workflow-Run Details (if provided)
        if: ${{ inputs.workflow_run }}
        run: |
          echo "Triggered from: [${{ fromJson(inputs.workflow_run).name }} - #${{ fromJson(inputs.workflow_run).run_number }}](${{ fromJson(inputs.workflow_run).html_url }})" >> $GITHUB_STEP_SUMMARY

      - name: Print a welcome message
        run: echo "Welcome to the Playwright Action!"

      - name: Print the current date
        run: echo "Today's date is $(date)"

      - name: Print a goodbye message
        run: echo "Goodbye from the Playwright Action!"