name: "Playwright Action"
description: "Run Playwright tests"

inputs:
  base_url:
    description: "Base URL for the action"
    required: true
  run_environment:
    description: "Environment for the action"
    required: true
  workflow_run_url:
    description: "Workflow run for the action"
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: print inputs
      shell: bash
      run: |
        echo "Base URL: ${{ inputs.base_url }}"
        echo "Environment: ${{ inputs.run_environment }}"

    - name: Create Summary
      id: create_summary
      shell: bash
      run: |
        echo "## Summary" >> $GITHUB_STEP_SUMMARY
        echo "Base URL: ${{ inputs.base_url }}" >> $GITHUB_STEP_SUMMARY
        echo "Environment: ${{ inputs.run_environment }}" >> $GITHUB_STEP_SUMMARY
        echo "Workflow run URL: ${{ inputs.workflow_run_url }}" >> $GITHUB_STEP_SUMMARY
