name: "Playwright Action"

on:
  workflow_call:
    inputs:
      base_url:
        description: "Base URL for the action"
        required: true
        type: string
      environment:
        description: "Environment for the action"
        required: true
        type: string
      workflow_run_url:
        description: "Workflow run for the action"
        required: false
        type: string

env:
  BASE_URL: ${{ inputs.base_url }}
  ENVIRONMENT: ${{ inputs.environment }}
  WORKFLOW_RUN_URL: ${{ inputs.workflow_run_url }}

jobs:
  playwright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: print inputs
        run: |
          echo "Base URL: $BASE_URL"
          echo "Environment: $ENVIRONMENT"

      - name: Create Summary
        id: create_summary
        run: |
          echo "## Summary" >> $GITHUB_STEP_SUMMARY
          echo "Base URL: $$BASE_URL" >> $GITHUB_STEP_SUMMARY
          echo "Environment: $ENVIRONMENT" >> $GITHUB_STEP_SUMMARY
          echo "Workflow run URL: $WORKFLOW_RUN_URL" >> $GITHUB_STEP_SUMMARY