name: "Playwright Action"
description: "An example action that outputs messages to the console."

on:
  workflow_call:
    inputs:
      base_url:
        description: "Base URL for the action"
        required: true
        type: string
      environment:
        description: "Environment for the action"
        required: true
        type: string
      workflow_run_url:
        description: "Workflow run for the action"
        required: false
        type: string
    # secrets:
    #   e2e_user:
    #     description: "E2E user secret"
    #     required: true
    #   e2e_password:
    #     description: "E2E password secret"
    #     required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: print inputs
        run: |
          echo "Base URL: ${{ inputs.base_url }}"
          echo "Environment: ${{ inputs.environment }}"

      - name: Print a welcome message
        run: echo "Welcome to the Playwright Action!"

      - name: Print the current date
        run: echo "Today's date is $(date)"

      - name: Print a goodbye message
        run: echo "Goodbye from the Playwright Action!"

      - name: Create Summary
        id: create_summary
        run: |
          echo "## Summary" >> $GITHUB_STEP_SUMMARY
          echo "Base URL: ${{ inputs.base_url }}" >> $GITHUB_STEP_SUMMARY
          echo "Environment: ${{ inputs.environment }}" >> $GITHUB_STEP_SUMMARY
          echo "Workflow run URL: ${{ inputs.workflow_run_url }}" >> $GITHUB_STEP_SUMMARY