name: "Playwright Action"

inputs:
  base_url:
    description: "Base URL for the action"
    required: true
    type: string
  env:
    description: "Environment for the action"
    required: true
    type: string
  workflow_run_url:
    description: "Workflow run for the action"
    required: false
    type: string

env:
  BASE_URL: ${{ inputs.base_url }}
  ENVIRONMENT: ${{ inputs.environment }}
  WORKFLOW_RUN_URL: ${{ inputs.workflow_run_url }}

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      shell: bash

    - name: print inputs
      shell: bash
      run: |
        echo "Base URL: ${{ inputs.base_url }}"
        echo "Environment: ${{ inputs.environment }}"

    - name: Create Summary
      id: create_summary
      shell: bash
      run: |
        echo "## Summary" >> $GITHUB_STEP_SUMMARY
        echo "Base URL: ${{ inputs.base_url }}" >> $GITHUB_STEP_SUMMARY
        echo "Environment: ${{ inputs.environment }}" >> $GITHUB_STEP_SUMMARY
        echo "Workflow run URL: ${{ inputs.workflow_run_url }}" >> $GITHUB_STEP_SUMMARY
