name: "Playwright Action"
description: "An example action that outputs messages to the console."

on:
  workflow_call:
    inputs:
      workflow-run:
        description: "The workflow run object. i.e. github.event.workflow_run."
        required: false

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Set Workflow Run Environment Variable
        run: |
          echo "WORKFLOW_RUN=${{ inputs.workflow-run }}" >> $GITHUB_ENV

      - name: Print Workflow-Run Details (if provided)
        if: ${{ env.WORKFLOW_RUN }}
        run: |
          echo "Triggered from: [${{ fromJson(env.WORKFLOW_RUN).name }} - #${{ fromJson(env.WORKFLOW_RUN).run_number }}](${{ fromJson(env.WORKFLOW_RUN).html_url }})" >> $GITHUB_STEP_SUMMARY

      - name: Print a welcome message
        run: echo "Welcome to the Playwright Action!"

      - name: Print the current date
        run: echo "Today's date is $(date)"

      - name: Print a goodbye message
        run: echo "Goodbye from the Playwright Action!"