name: Reusable workflow example
run-name: example workflow

on:
  workflow_call:
    inputs:
      test-value:
        required: true
        type: string

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: echo some stuff
        run: |
          echo "This is a reusable workflow example"
          echo "test value: ${{ inputs.test-value }}"
