name: "Test - Check Deploy Environments"

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  JSON: ${{ toJson(github.event) }}

jobs:
  check-deployments:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: kghafari/my-actions/src/env-check@main
        with:
          github_repo: kghafari/testbot
          environments_to_check: "dev,staging,prod"
